### ISSUE TITLE
DataLoader worker (pid(s) ...) exited unexpectedly

### ISSUE THREAD

**Issue by cuongngm** [WenmuZhou/DBNet.pytorch#108]
I train DBNet follow your tutorial but meet with error. The RAM memory increase and crash. How can i do to fix it?
 `2021-01-11 03:46:28,767 DBNet.pytorch INFO: train with device cuda and pytorch 1.4.0
2021-01-11 03:46:33.290082: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2021-01-11 03:46:37,160 DBNet.pytorch INFO: train dataset has 800 samples,800 in dataloader, validate dataset has 187 samples,187 in dataloader
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 761, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/usr/lib/python3.6/queue.py", line 173, in get
    self.not_empty.wait(remaining)
  File "/usr/lib/python3.6/threading.py", line 299, in wait
    gotit = waiter.acquire(True, timeout)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 1454) is killed by signal: Killed. 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 78, in <module>
    main(config)
  File "tools/train.py", line 59, in main
    trainer.train()
  File "/content/drive/My Drive/DBNet.pytorch/base/base_trainer.py", line 104, in train
    self.epoch_result = self._train_epoch(epoch)
  File "/content/drive/My Drive/DBNet.pytorch/trainer/trainer.py", line 46, in _train_epoch
    for i, batch in enumerate(self.train_loader):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 841, in _next_data
    idx, data = self._get_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 798, in _get_data
    success, data = self._try_get_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 774, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 1454) exited unexpectedly`

Another question: Can i train the model with only coordinates text and without the label text? Do it influence?

**Comment by WenmuZhou** [comment]
reduce your num_workers

**Comment by cuongngm** [comment]
i set to 0, 2, 4 but it still don't work

**Comment by cuongngm** [comment]
i edit the code without the annotations text and happened this error, add annotations text and it work.
