### ISSUE TITLE
加载预训练数据集时报错

### ISSUE THREAD

**Issue by bowenliu1996** [WenmuZhou/DBNet.pytorch#124]
Traceback (most recent call last):
  File "tools/train.py", line 79, in <module>
    main(config)
  File "tools/train.py", line 37, in main
    train_loader = get_dataloader(config['dataset']['train'], config['distributed'])
  File "/home/bowen/下载/DBNet.pytorch-master/data_loader/__init__.py", line 84, in get_dataloader
    _dataset = get_dataset(data_path=data_path, module_name=dataset_name, transform=img_transfroms, dataset_args=dataset_args)
  File "/home/bowen/下载/DBNet.pytorch-master/data_loader/__init__.py", line 24, in get_dataset
    **dataset_args)
  File "/home/bowen/下载/DBNet.pytorch-master/data_loader/dataset.py", line 102, in __init__
    self.dataRoot = pathlib.Path(data_path)
  File "/home/bowen/anaconda3/envs/dbnet/lib/python3.6/pathlib.py", line 1001, in __new__
    self = cls._from_parts(args, init=False)
  File "/home/bowen/anaconda3/envs/dbnet/lib/python3.6/pathlib.py", line 656, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/home/bowen/anaconda3/envs/dbnet/lib/python3.6/pathlib.py", line 640, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not list

TypeError: expected str, bytes or os.PathLike object, not list

**Comment by bowenliu1996** [comment]
Please help me solve this problem，Thank U！

**Comment by wayne2tech** [comment]
把路径中的中文改成英文试试？相对路径换成绝对路径？ 总有一款适合你
