### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by kangbo750** [WenmuZhou/DBNet.pytorch#137]
Traceback (most recent call last):
  File "/content/drive/MyDrive/DBnet/DBNet.pytorch-master/tools/train.py", line 78, in <module>
    main(config)
  File "/content/drive/MyDrive/DBnet/DBNet.pytorch-master/tools/train.py", line 37, in main
    train_loader = get_dataloader(config['dataset']['train'], config['distributed'])
  File "/content/drive/MyDrive/DBnet/DBNet.pytorch-master/data_loader/__init__.py", line 84, in get_dataloader
    _dataset = get_dataset(data_path=data_path, module_name=dataset_name, transform=img_transfroms, dataset_args=dataset_args)
  File "/content/drive/MyDrive/DBnet/DBNet.pytorch-master/data_loader/__init__.py", line 24, in get_dataset
    **dataset_args)
  File "/content/drive/MyDrive/DBnet/DBNet.pytorch-master/data_loader/dataset.py", line 17, in __init__
    super().__init__(data_path, img_mode, pre_processes, filter_keys, ignore_tags, transform)
  File "/content/drive/MyDrive/DBnet/DBNet.pytorch-master/base/base_dataset.py", line 18, in __init__
    assert item in self.data_list[0], 'data_list from load_data must contains {}'.format(item_keys)
IndexError: list index out of range
请问一下有没有老哥知道这个怎么解决？

**Comment by Lyf1122** [comment]
你好，请问你是怎么解决的呢？
