### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by wwp-max** [WenmuZhou/DBNet.pytorch#146]
Traceback (most recent call last):
  File "C:/Users/Lenovo/DBNet.pytorch/tools/train.py", line 79, in <module>
    main(config)
  File "C:/Users/Lenovo/DBNet.pytorch/tools/train.py", line 41, in main
    validate_loader = get_dataloader(config['dataset']['validate'], False)
  File "C:\Users\Lenovo\DBNet.pytorch\data_loader\__init__.py", line 84, in get_dataloader
    _dataset = get_dataset(data_path=data_path, module_name=dataset_name, transform=img_transfroms, dataset_args=dataset_args)
  File "C:\Users\Lenovo\DBNet.pytorch\data_loader\__init__.py", line 23, in get_dataset
    s_dataset = getattr(dataset, module_name)(transform=transform, data_path=data_path,
  File "C:\Users\Lenovo\DBNet.pytorch\data_loader\dataset.py", line 17, in __init__
    super().__init__(data_path, img_mode, pre_processes, filter_keys, ignore_tags, transform)
  File "C:\Users\Lenovo\DBNet.pytorch\base\base_dataset.py", line 18, in __init__
    assert item in self.data_list[0], 'data_list from load_data must contains {}'.format(item_keys)
IndexError: list index out of range

配置文件修改成功后，运行train.py就报了这个错误，请问有人知道是什么原因吗？

**Comment by ming-eng** [comment]
数据格式不对

**Comment by KKjiaming** [comment]
不是数据格式不对，是你的util里面的get_datalist写错了：line = line.strip('\n').replace('.jpg ', '.jpg\t').split('\t') 。train.txt 的格式是img \t gt 的话replace之后就有两个\t。作者改一下源码把replace去掉或者把train.txt 的格式改一下

**Comment by Wangqi12138** [comment]
@KKjiaming  改完还是不太对

**Comment by WenmuZhou** [comment]
debug看看哦，很简单的
