### ISSUE TITLE
predict.py

### ISSUE THREAD

**Issue by xiaomingxige** [WenmuZhou/DBNet.pytorch#153]
125行save_resut应该为save_result

**Comment by ChihabEddine98** [comment]
Hey ! , yeah I had the same observation I think you can make a pull request while waiting for its validation.

**Comment by aswa123** [comment]
do you know why there is a error while running this file?
Traceback (most recent call last):
  File "/home/swap/miniconda3/envs/DB-master/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3361, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-c707bbee3e3a>", line 1, in <cell line: 1>
    runfile('/home/swap/Downloads/DBNet.pytorch-master/tools/predict.py', wdir='/home/swap/Downloads/DBNet.pytorch-master/tools')
  File "/home/swap/.local/share/JetBrains/Toolbox/apps/PyCharm-C/ch-0/202.7660.27/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/swap/.local/share/JetBrains/Toolbox/apps/PyCharm-C/ch-0/202.7660.27/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/swap/Downloads/DBNet.pytorch-master/tools/predict.py", line 142, in <module>
    for img_path in tqdm(get_file_list(args.input_folder, p_postfix=['.jpg'])):
  File "/home/swap/Downloads/DBNet.pytorch-master/utils/util.py", line 23, in get_file_list
    assert os.path.exists(folder_path) and os.path.isdir(folder_path)
AssertionError

**Comment by ChihabEddine98** [comment]
@aswa123 Hey , did you make a folder named input in which your input images have "**.JPG**" extension ? that occurred for me when I tried to work with other format files that you can easily change in line `142`

**Comment by goseesomething** [comment]
The reason is the /DBNet.pytorch/tools/predict.py line 125  save_resut  >> save_result
