### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by jihuodexiaoyang** [WenmuZhou/DBNet.pytorch#170]
root@dsw-239190-b6866c49-vs5c8:/mnt/workspace/downloads/137084/DBNet.pytorch# CUDA_VISIBLE_DEVICES=0 python3 tools/train.py --config_file "config/icdar2015_resnet18_FPN_DBhead_polyLR.yaml"  # 单GPU训练Traceback (most recent call last):
  File "tools/train.py", line 78, in <module>
    main(config)
  File "tools/train.py", line 37, in main
    train_loader = get_dataloader(config['dataset']['train'], config['distributed'])
  File "/mnt/workspace/downloads/137084/DBNet.pytorch/data_loader/__init__.py", line 84, in get_dataloader
    _dataset = get_dataset(data_path=data_path, module_name=dataset_name, transform=img_transfroms, dataset_args=dataset_args)
  File "/mnt/workspace/downloads/137084/DBNet.pytorch/data_loader/__init__.py", line 24, in get_dataset
    **dataset_args)
  File "/mnt/workspace/downloads/137084/DBNet.pytorch/data_loader/dataset.py", line 17, in __init__
    super().__init__(data_path, img_mode, pre_processes, filter_keys, ignore_tags, transform)
  File "/mnt/workspace/downloads/137084/DBNet.pytorch/base/base_dataset.py", line 18, in __init__
    assert item in self.data_list[0], 'data_list from load_data must contains {}'.format(item_keys)
IndexError: list index out of range 
训练时出现此错误

**Comment by HappyBruce1** [comment]
你好，请问您解决了吗，我遇到了跟你一样的问题

**Comment by WenmuZhou** [comment]
大概率是数据路径问题

**Comment by HappyBruce1** [comment]
是的，是格式的问题，我的已经解决

**Comment by Wangqi12138** [comment]
请问怎么解决的啊？求告知

**Comment by HappyBruce1** [comment]
格式问题，你可以看下你数据集的格式

**Comment by Wangqi12138** [comment]
我是用的作者的数据，不懂怎么改了

**Comment by zhangqiqi1228** [comment]
> 我是用的作者的数据，不懂怎么改了

我之前也遇到了相同的问题，最终排查是train.txt和test.txt生成的时候的路径不对。
你可以排查一下：
1. datasets文件夹下要直接存放四个文件：train和test文件夹，train.txt和train.txt。建议不要在datasets下增加不同数据集文件夹，例如：./datasets/ICDAR2015/train.txt这种不行。
2. train.txt和test.txt的路径是否正确，尤其看看正反斜杠问题。我之前是在wins上生成的trian.txt，忘记替换正反斜杠了，在linux上就报错了。
3. 实在不行，你把trian.txt和test.txt中的路径改成绝对路径吧。
希望对你有帮助！
