### ISSUE TITLE
训练时，反向传播错误

### ISSUE THREAD

**Issue by TALQinYong** [WenmuZhou/DBNet.pytorch#18]
Traceback (most recent call last):
  File "train_eval_test/train.py", line 80, in <module>
    main(config)
  File "train_eval_test/train.py", line 64, in main
    trainer.train()
  File "/share/yongqin/experimentplan/PDBNet/trainer/base_trainer.py", line 103, in train
    self.epoch_result = self._train_epoch(epoch)
  File "/share/yongqin/experimentplan/PDBNet/trainer/trainer.py", line 85, in _train_epoch
    loss_dict['loss'].backward()
  File "/root/miniconda3/envs/py36/lib/python3.6/site-packages/torch/tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/root/miniconda3/envs/py36/lib/python3.6/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [4, 640, 640]], which is output 0 of SliceBackward, is at version 2; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

**Comment by MingdongHe** [comment]
我在使用FPEM_FFM作为neck，ShuffleNetV2作为backbone时遇到这个问题，我将FPEM_FFM.py中的代码修改成图中的代码，问题解决了。
![image](https://github.com/user-attachments/assets/1da90e3c-d958-40a9-acff-dc3cc9ec8ce3)
