### ISSUE TITLE
灰度图训练报错

### ISSUE THREAD

**Issue by winsonxxxx** [WenmuZhou/DBNet.pytorch#32]
您好，我拿icdar2015，icdar2015_dcn_resnet18_FPN_DBhead_polyLR.yaml里面img_mode: RGB是能正常跑起来的；但是我想尝试灰度图输入，所以把img_mode: RGB改成了img_mode: GRAY；但是会报如下错误：

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/project/OCR/DBNet.pytorch/train.py", line 74, in <module>
    main(config)
  File "D:/project/OCR/DBNet.pytorch/train.py", line 58, in main
    trainer.train()
  File "D:\project\OCR\DBNet.pytorch\base\base_trainer.py", line 103, in train
    self.epoch_result = self._train_epoch(epoch)
  File "D:\project\OCR\DBNet.pytorch\trainer\trainer.py", line 46, in _train_epoch
    for i, batch in enumerate(self.train_loader):
  File "D:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 345, in __next__
    data = self._next_data()
  File "D:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 841, in _next_data
    idx, data = self._get_data()
  File "D:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 808, in _get_data
    success, data = self._try_get_data()
  File "D:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 774, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 38096) exited unexpectedly

请问目前的代码怎么修改，跑通灰度图训练？

**Comment by WenmuZhou** [comment]
已经支持
