### ISSUE TITLE
随机裁剪的图片预处理，程序被强行kill

### ISSUE THREAD

**Issue by Eric-hhh** [WenmuZhou/DBNet.pytorch#58]
训练时在yaml中设置图片预处理的方式如下
pre_processes:
            - type: EastRandomCropData
              args:
                size:  
                max_tries: 5
结果进程总是被强制kill（sigkill：9）

**Comment by Eric-hhh** [comment]
<img width="327" alt="image" src="https://user-images.githubusercontent.com/67671893/89012929-9426db00-d345-11ea-8485-1f167f55080f.png">
书写格式如图，应该不是格式的问题吧，我是把军哥你的那个resize注释掉了，按照你那个写的

**Comment by WenmuZhou** [comment]
看起来没啥问题，你那边能debug吗

**Comment by Eric-hhh** [comment]
<img width="357" alt="image" src="https://user-images.githubusercontent.com/67671893/89029822-cd6d4400-d361-11ea-9c1a-eb82aa7b8b8e.png">
这样不加参数行就能跑通了，很奇怪

**Comment by WenmuZhou** [comment]
估计是你那个size参数没传值把

**Comment by LXLun** [comment]
问一下加上随机裁剪为什么会报这个
`Traceback (most recent call last):
  File "tools/train.py", line 78, in <module>
    main(config)
  File "tools/train.py", line 59, in main
    trainer.train()
  File "/home/luoxilun/lxl/DBNet.pytorch/base/base_trainer.py", line 104, in train
    self.epoch_result = self._train_epoch(epoch)
  File "/home/luoxilun/lxl/DBNet.pytorch/trainer/trainer.py", line 60, in _train_epoch
    loss_dict = self.criterion(preds, batch)
  File "/home/luoxilun/lxl/dbnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/luoxilun/lxl/DBNet.pytorch/models/losses/DB_loss.py", line 33, in forward
    loss_shrink_maps = self.bce_loss(shrink_maps, batch['shrink_map'], batch['shrink_mask'])
KeyError: 'shrink_map'`
