### ISSUE TITLE
训练时候报错 too many values to unpack

### ISSUE THREAD

**Issue by xxllp** [WenmuZhou/DBNet.pytorch#59]
> 2020-07-31 18:54:58,102 DBNet.pytorch INFO: train with device cuda and pytorch 1.4.0
2020-07-31 18:55:05,093 DBNet.pytorch INFO: train dataset has 14 samples,14 in dataloade           r, validate dataset has 14 samples,14 in dataloader
2020-07-31 18:55:08,188 DBNet.pytorch INFO: [1/1200], [10/14], global_step: 10, speed: 3           .2 samples/sec, acc: 0.5041, iou_shrink_map: 0.1341, loss: 4.2495, loss_shrink_maps: 1.8           940, loss_threshold_maps: 0.1414, loss_binary_maps: 0.9412, , lr:0.00047619, time:3.09
2020-07-31 18:55:08,546 DBNet.pytorch INFO: [1/1200], train_loss: 6.5545, time: 3.4459,            lr: 0.0005396825396825396
test model:   0%|                                                | 0/14 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "tools/train.py", line 78, in <module>
    main(config)
  File "tools/train.py", line 59, in main
    trainer.train()
  File "/home/mlp/xxl/DBNet.pytorch/base/base_trainer.py", line 107, in train
    self._on_epoch_finish()
  File "/home/mlp/xxl/DBNet.pytorch/trainer/trainer.py", line 157, in _on_epoch_finish
    recall, precision, hmean = self._eval(self.epoch_result['epoch'])
  File "/home/mlp/xxl/DBNet.pytorch/trainer/trainer.py", line 137, in _eval
    boxes, scores = self.post_process(batch, preds,is_output_polygon=self.metric_cls.is_           output_polygon)
  File "/home/mlp/xxl/DBNet.pytorch/post_processing/seg_detector_representer.py", line 3           8, in __call__
    boxes, scores = self.boxes_from_bitmap(pred[batch_index], segmentation[batch_index],            width, height)
  File "/home/mlp/xxl/DBNet.pytorch/post_processing/seg_detector_representer.py", line 1           05, in boxes_from_bitmap
    contours, _ = cv2.findContours((bitmap * 255).astype(np.uint8), cv2.RETR_LIST, cv2.C           HAIN_APPROX_SIMPLE)
ValueError: too many values to unpack (expected 2)

**Comment by WenmuZhou** [comment]
opencv 升级一下

**Comment by xxllp** [comment]
可以了 ，还有个比较迷惑的就是config里面的各文件到底有啥区别  有没有详细点的介绍啊
