### ISSUE TITLE
怎样导出pt模型

### ISSUE THREAD

**Issue by Ri-Yue-Shui-Hua** [WenmuZhou/DBNet.pytorch#70]
大牛你好，我想知道怎么保存pt模型文件，我看到代码predict.py中有下面一段代码应该是保存pt模型文件用的，请问在哪里怎么调用呢？ 原谅我一个刚入门的小白，提问这么初级的问题。

def save_depoly(model, input, save_path):
    traced_script_model = torch.jit.trace(model, input)
    traced_script_model.save(save_path)

**Comment by Ri-Yue-Shui-Hua** [comment]
这个问题我已经解决了。但是有一个问题，模型固化为pt后，在c++下调用输入图片的尺寸只能归一化到固化模型时使用的尺寸，否则就会报错。猜测固化模型时只保留了固化模型时的参数，超出范围就会报错。好奇的是pytorch为什么可以这么灵活接受不同尺寸的输入，或者固化模型时还有更好的方法可以跟ytorch保持一致？

**Comment by Crystalxd** [comment]
能问一下你是如何解决的吗？我在转换的过程中总是报错：
Traceback (most recent call last):
  File "tools/predict.py", line 146, in <module>
    save_depoly(model, input, save_path)
  File "tools/predict.py", line 113, in save_depoly
    traced_script_model = torch.jit.trace(model, input)
  File "/home/dl/anaconda3/envs/yv5/lib/python3.7/site-packages/torch/jit/__init__.py", line 903, in trace
    name = _qualified_name(func)
  File "/home/dl/anaconda3/envs/yv5/lib/python3.7/site-packages/torch/_jit_internal.py", line 682, in _qualified_name
    name = obj.__name__
AttributeError: 'Pytorch_model' object has no attribute '__name__'
是否和torch版本有关？我是pip install torch==1.4来安装的pytorch

**Comment by Ri-Yue-Shui-Hua** [comment]
看样子是你调用的位置或者传参不对。
下面这样可做参考
&nbsp;# 初始化网络
&nbsp; &nbsp; model = Pytorch_model(args.model_path, post_p_thre=args.thre, gpu_id=0)
&nbsp; &nbsp; input = torch.rand(1, 3, 736, 736).cuda() # wmz&nbsp;
&nbsp; &nbsp; save_depoly(model.model.eval(), input, "dbnet.pt")





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WenmuZhou/DBNet.pytorch"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月9日(星期三) 下午4:45
收件人:&nbsp;"WenmuZhou/DBNet.pytorch"<DBNet.pytorch@noreply.github.com&gt;;
抄送:&nbsp;"十二"<1217849284@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [WenmuZhou/DBNet.pytorch] 怎样导出pt模型 (#70)





 
能问一下你是如何解决的吗？我在转换的过程中总是报错：
 Traceback (most recent call last):
 File "tools/predict.py", line 146, in 
 save_depoly(model, input, save_path)
 File "tools/predict.py", line 113, in save_depoly
 traced_script_model = torch.jit.trace(model, input)
 File "/home/dl/anaconda3/envs/yv5/lib/python3.7/site-packages/torch/jit/init.py", line 903, in trace
 name = _qualified_name(func)
 File "/home/dl/anaconda3/envs/yv5/lib/python3.7/site-packages/torch/_jit_internal.py", line 682, in _qualified_name
 name = obj.name
 AttributeError: 'Pytorch_model' object has no attribute 'name'
 是否和torch版本有关？我是pip install torch==1.4来安装的pytorch

**Comment by Crystalxd** [comment]
非常感谢！
